### ISSUE TITLE
Loading vehicle individual parameters from `$(vehicle_id)/$(sample_sensor_kit)` does not make sense?

### ISSUE THREAD

**Issue by VRichardJP** [autowarefoundation/autoware_launch#215]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I'm convinced that this is not my fault but a bug.

### Description

From a recent change, `autoware_launch.xml` now loads vehicle unique parameters from [`$(find-pkg-share individual_params)/config/$(var vehicle_id)/$(var sensor_model)`](https://github.com/autowarefoundation/autoware_launch/blob/a50d074533e5a957f663d8d5393120a2553fae7c/autoware_launch/launch/autoware.launch.xml#L63).

If `vehicle_id` is the id of a unique vehicle (= vehicle model + sensor kit + vehicle "uniqueness"), `sensor_model` is fundamentaly redundant. No?

Wouldn't it make more sense to use this instead: `$(find-pkg-share individual_params)/config/$(var sensor_model)/$(var vehicle_model)/$(var vehicle_id)`. The order makes more sense to me as the sensor kit placement (calibration) 100% depends on the vehicle model. Also, "individual" vehicle params totally depend on the sensor kit and vehicle model as well.

For example, the "default" (= generic) calibration for the sample vehicle/sensor_kit would be placed in `individual_params/sample_sensor_kit/sample_vehicle/default` instead of the current `individual_params/default/sample_sensor_kit`

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to reproduce

N/A

**Comment by takayuki5168** [comment]
@VRichardJP 

> From a recent change, autoware_launch.xml now loads vehicle unique parameters from [$(find-pkg-share individual_params)/config/$(var vehicle_id)/$(var sensor_model)](https://github.com/autowarefoundation/autoware_launch/blob/a50d074533e5a957f663d8d5393120a2553fae7c/autoware_launch/launch/autoware.launch.xml#L63).

First of all, the change you mentioned has been merged recently, but the directory structure of individual_params did not change as follows, but of course, we can discuss a better directory structure.
https://github.com/autowarefoundation/autoware_individual_params/tree/main/individual_params/config/default/sample_sensor_kit

> If vehicle_id is the id of a unique vehicle (= vehicle model + sensor kit + vehicle "uniqueness")
This is correct.

> , sensor_model is fundamentaly redundant. No?

In sensor_model, there is a calibration file which depends on the unique vehicle, right? Therefore, it's not redundant.
Sorry if I misunderstood something.

> Wouldn't it make more sense to use this instead: $(find-pkg-share individual_params)/config/$(var sensor_model)/$(var vehicle_model)/$(var vehicle_id)`

Regarding TIER IV's product, we prepare one individual_params repository for each vehicle (xxx taxi). Therefore, I felt `$(find-pkg-share individual_params)/config/$(var sensor_model)/$(var vehicle_id)` sounds better since the vehicle_model variable does not change in a autoware_individual_params repository.

Does your proposal `$(find-pkg-share individual_params)/config/$(var sensor_model)/$(var vehicle_model)/$(var vehicle_id)` assume that in a autoware_individual_params repository, you contain some vehicles' params like xxx taxi, yyy bus, ..., right?

**Comment by VRichardJP** [comment]
Maybe it makes more sense with a few examples:
- `vehicle_model`: yamaha golfcart model XXX, Lexus model YYY, etc. In other words the vehicle body, mechanical specs, etc
- `sensor_model`: AWF reference sensor kit, third-party XXX sensor kit, etc. In other words the list of sensors, preprocessing, but actual placement of the kit depends on the vehicle.
- `vehicle_id`: the integrated vehicle (= unique `vehicle_model` x `sensor_model` combination + adjusted calibration). 
 
Let's say I have a golfcart with AWF sensor kit with id "A". Then `vehicle_id=A` designates nothing but this very unique golfcart that has been integrated/tuned with the AWF sensor kit. If I change the vehicle model or the sensor kit, it is no more "A". In that sense, `A/awf_sensor_kit/*.yaml` is "redundant" (over just `A/*.yaml`). 

But maybe for Tier IV the `vehicle_id` is like a VIN number? In other word, if we swap the sensor kit, vehicle_id is unchanged? From experience with other AD platforms, when the sensor kit is touched/replaced a new calibration is necessary. So as soon as I put back my `awf_sensor_kit` on my vehicle "A", the parameters in `A/awf_sensor_kit` are obsolete. 

Coming back to `A/*.yaml`: if I have a lot of vehicles, it may be difficult with just a name like `config/A/*.yaml` to understand which vehicle model and which sensor kit is beind used. Instead, it makes sense to organize individual params like this: `config/golfcart_XXX/awf_sensor_kit_v2/A/*.yaml`.

**Comment by takayuki5168** [comment]
@VRichardJP Let me confirm that my understanding meets yours first.

> Let's say I have a golfcart with AWF sensor kit with id "A". Then vehicle_id=A designates nothing but this very unique golfcart that has been integrated/tuned with the AWF sensor kit.

Each vehicle, which has its own vehicle_id, has different sensor calibration parameter.
For example, assuming that the vehicle_model and sensor_model are the same, there are two vehicles whose vehicle ids are A and B.
We assume that the Lidar's pitch angle on the sensor_model is supposed to be 90 degrees. But with the fine sensor calibration, the pitch angle on A may be 90.1 degrees and B 89.9 degrees. So we want to use these calibrated true pitch angles.

Do you consider such a case?

**Comment by VRichardJP** [comment]
Yes, exactly. That is why you would have:
- `config/golfcart_XXX/awf_sensor_kit_v2/A/*.yaml` (pitch = 89.9 here)
- `config/golfcart_XXX/awf_sensor_kit_v2/B/*.yaml` (pitch = 90.1 here)
- `config/golfcart_XXX/awf_sensor_kit_v2/default/*.yaml` ("ideal" calibration: pitch= 90)

**Comment by kenji-miyake** [comment]
If I remember correctly, the reason why we adopted `$(find-pkg-share individual_params)/config/$(var vehicle_id)/$(var sensor_model)` is, it's useful if `vehicle_id` comes first.
    
For example, when we build a Web-based parameter management system, it needs to collect all parameters related to a specific vehicle.
In that situation, it's easier if everything is under `config/$(var vehicle_id)/`.

> If I change the vehicle model or the sensor kit, it is no more "A". In that sense, A/awf_sensor_kit/*.yaml is "redundant" (over just A/*.yaml).

Hmm, I feel it's not true. The vehicle is still "A" even if we change the sensor kit. I believe you should maintain the parameters under `config/vehicle_id_A`.

The sense of `config/vehicle_id_A/sensor_kit_A/` is "since the vehicle `vehicle_id_A` uses `sensor_kit_A`, it should have the parameter set of `sensor_kit_A`".
If we replace `sensor_kit_A` with `sensor_kit_B`, remove `config/vehicle_id_A/sensor_kit_A/` and add `config/vehicle_id_A/sensor_kit_B/`.

(If you replace the vehicle model itself, then you should give a new ID to the vehicle, so I think the old parameters aren't redundant.)

**Comment by VRichardJP** [comment]
@kenji-miyake 
I finally gets it. `config/$(var vehicle_id)/$(var sensor_model)` is not a _categorization_, a way to organize many vehicles as I described [previously](https://github.com/autowarefoundation/autoware_launch/issues/215#issuecomment-1436545565), but a _composition_: vehicle A has a specific configuration for its component `sensor_kit`, but it may also have some vehicle specific parameters for another component `system_manager`, in which cases the parameters would be put in `config/vehicle_id_A/system_manager/*.yaml` and so on. Now it looks obvious to me.
