### ISSUE TITLE
Parameter management

### ISSUE THREAD

**Issue by takayuki5168** [autowarefoundation/autoware_launch#66]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/autowarefoundation/autoware/blob/main/CONTRIBUTING.md).
- [X] I've searched other issues and no duplicate issues were found.
- [X] I've agreed with the maintainers that I can plan this task.

### Description

Currently, autoware has its parameters only in autoware.universe.
That means, when we want to integrate autoware to a specific vehicle and modify parameters, we have to fork autoware.universe which also has a lot of code other than parameters.

Now we have the autoware_launch repository referring to autoware.universe.
We, TIER IV, concluded that it would be better for autoware_launch to have parameters of autoware.universe, and modify parameters for integration.
With this integration procedure, we don't have to fork autoware.universe.

This idea is described here.
https://autowarefoundation.github.io/autoware-documentation/pr-171/contributing/coding-guidelines/ros-nodes/parameters/

### Purpose

In order to easily modify autoware parameters (e.g. for integration to a specific vehicle)

### Possible approaches

- [ ] Add config files to launch autoware in the `autoware_launch` package.
    - designate autoware_launch/config when launching autoware via autoware_launch (using tier4_*_launch_param_path argument)
        - https://github.com/autowarefoundation/autoware_launch/pull/67
    - each module launch receives tier4_*_launch_param_path from autoware.launch.xml
        - system: https://github.com/autowarefoundation/autoware.universe/pull/1411
        - localization: https://github.com/autowarefoundation/autoware.universe/pull/1404
        - perception: https://github.com/autowarefoundation/autoware.universe/pull/1394
        - planning: https://github.com/autowarefoundation/autoware.universe/pull/1337
        - control: https://github.com/autowarefoundation/autoware.universe/pull/1432
    - create sync PR (e.g. for planning module: awf/autoware.universe/launch/tier4_planning_launch/config -> awf/autoware_launch/autoware_launch/config/tier4_planning_launch)
        - https://github.com/autowarefoundation/autoware_launch/pull/64
    - enable sync PR
        - https://github.com/autowarefoundation/autoware_launch/pull/65
- [ ] Add documentation of all parameters' descriptions of autoware and how to manage them.
    - https://github.com/autowarefoundation/autoware-documentation/pull/171
    - https://autowarefoundation.github.io/autoware-documentation/pr-171/contributing/coding-guidelines/ros-nodes/parameters/
- [ ] Add integration procedure of autoware with these parameters.
    - https://github.com/autowarefoundation/autoware-documentation/pull/172
    - https://autowarefoundation.github.io/autoware-documentation/pr-172/how-to-guides/how-to-integrate-autoware-with-your-vehicle/

### Definition of done

All checkboxes of the possible approaches are closed.

**Comment by takayuki5168** [comment]
@xmfcx Hi, I'm Takayuki Murooka from the planning/control team at TIER IV

We, TIER IV, concluded how to manage parameters of autoware described in this issue and the following document.
https://autowarefoundation.github.io/autoware-documentation/pr-171/contributing/coding-guidelines/ros-nodes/parameters/

Currently, we are working on creating this parameters' management system described in "Possible approaches".

Miyake-san suggested to me that I should share this with you. Do you have any questions or opinions?

**Comment by xmfcx** [comment]
@takayuki5168 @kenji-miyake

Hi Murooka-san, nice to meet you.

I have been thinking about similar solutions for following issues I've faced with Autoware:

---
### Launch System and Parameters

- **It's easy miss to set some parameters**
- **Hard to figure out where the parameters are set**
- Launch system is too complicated
- Hard to create a launch configuration
- It's not clear which parameters are shared

### Node Management

- It's not clear what nodes
  - need to run
  - have crashed
  - are running
  - are functioning ok
  - belong to what high level module
  - depend on what nodes
- Hard to debug only a single node
---

This solution that you brought, solves the bold ones from the list about launch system and parameters.

I'm grateful to you for creating this solution and the automation of transferring of the param.yaml files.

---

I also had some ideas that are a bit broader but harder to achieve. I will try to list them:
- We should have a script/tool that automatically generates launch files from the nodes.
- We should have a list of shared parameters in the autoware.
  - If any parameter should be used in more than 1 node, it should be put to that list.
  - When creating a node, the developers should check that shared parameters list before declaring parameters.
- For a single package:
  - A single package can have multiple executables/nodes with different parameter sets.
  - It will probe the nodes for declared parameters
  - It will check the parameter list yaml file for each node `params/$NODE_NAME.yaml` to make sure it has all the declared parameters
  - It will check if shared parameters exist in the `$NODE_NAME.yaml`
    - If so, it will ignore it and use the one from the shared parameters list.
  - It will copy rest of the parameters from the file to a single large yaml file. (along with parameters from other nodes.)
- We will have a list of nodes that should be launched for a required configuration.
  - Like run whole stack, planning only, control test, lidar perception test etc.
  - These are just list of packages and nodes (without parameters).
  - Maybe we should first list all the possible nodes in the autoware workspace and mark the ones we see fit for these lists.
- This launch file generator tool will go through the nodes in the list for a specific configuration.
  - It then collects the parameters required for these nodes and puts them into a single large yaml file.

This method could automate launch file creation and eliminate human error while creating launch configurations.

It also requires us to set each node's `allow_undeclared_parameters` to `false`, so that all the declared params are defined before starting the node, [reference link](https://docs.ros.org/en/rolling/Concepts/About-ROS-2-Parameters.html#declaring-parameters).

There are things I haven't quite thought through:
- How to handle topic remapping in autoware
  - We as system developers know what nodes should connect to what through topics but how do we formalize this and automate launch file generation?
  - How do we visualize plug&play nature of nodes?
  - How do we offer alternative nodes for a given role?
    - 2 or more nodes can do the same job, how do we present these alternatives to system dev?
- How to handle composable nodes?
- Is it possible to list declared parameters of a node through CLI?

---

Sorry for the long post but I wanted to share my vision about the system configuration of the autoware. I think your solution is very precise and will work but I'd also like to hear your opinions about my thoughts too.

Thanks!

**Comment by takayuki5168** [comment]
@xmfcx Thank you for your reply.

This is my personal opinion.
Rather than an automatic launch files generator, I prefer having arguments in autoware_launch and deciding packages to launch.

For example, there is [obstacle_cruise_planner](https://github.com/autowarefoundation/autoware.universe/blob/15f5b57c336f8a349a8f4efa61bab1beaf12ee04/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py#L181-L200) and [obstacle_stop_planner](https://github.com/autowarefoundation/autoware.universe/blob/15f5b57c336f8a349a8f4efa61bab1beaf12ee04/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py#L138-L168) which have a similar function. One of this is selected by [cruise_planner argument](https://github.com/autowarefoundation/autoware.universe/blob/15f5b57c336f8a349a8f4efa61bab1beaf12ee04/launch/tier4_planning_launch/launch/scenario_planning/lane_driving/motion_planning/motion_planning.launch.py#L288-L290), which is hard to find for Autoware users.

My idea is having this cruise_planner argument in [tier4_planning_launch of autoware_launch/autoware.launch.xml](https://github.com/autowarefoundation/autoware_launch/blob/f434f80ce12e49e710aad47e870941209bc22a9c/autoware_launch/launch/autoware.launch.xml#L107-L114).
Like this, by changing arguments only in autoware_launch/autoware.launch.xml and also parameters in autoware_launch/config (, which do not exist currently), we can integrate Autoware to a specific vehicle.

I'm not sure if this fixed launch system (tier4_*_launch packages are fixed. Users will modify only autoware_launch package) is a good idea or not for OSS users to add new packages due to less flexibility of the launch system.
For more flexibility, the automatic launch generator will be much better.

**Comment by doganulus** [comment]
It would be good if we could launch Autoware from a single config file. For example,

```yaml
planning:
  default_param_path: "config/params.yaml" # loads default parameter values from the file
  some_common_planning_parameter: {value: 123 } # allows overriding the default value at top level

  obstacle_cruise_planner:
    default_param_path: "config/params.yaml" # loads default parameter values for the package
    some_obstacle_cruise_planner_parameter: {value: 45.6} # overrides the default value
    
control:
  default_param_path: "..."

perception:
  default_param_path: "..."
```

Surely there is much room for improvement, but a `docker-compose`-like experience would be a good target when managing parameters.

**Comment by kminoda** [comment]
We, TIER IV (including @takayuki5168, @kenji-miyake ), have reached to an alternative solution to the above-mentioned issue. We would like to reflect this improvement if we can agree with this modification.

@xmfcx @others who is interested in this topic
Let us know if you have any comments on this.

# Current issue (a quick brushup)

Current Autoware has following issue:
- If we want to customize the parameter depending on our vehicle, we need to take either of the approaches:
    1. Fork autoware.universe and change the parameter
    2. Fork autoware_launch and put a custom parameter in the repository
- Approach i increases the maintenance cost of your autoware.universe since you need to fork all the packages which is frequently updated by developers.
- Approach ii can confuse the developers since you are going to have three different parameters that look alike 
  - one in package, one in tier4_*_launch, and one in forked autoware_launch

# Proposal

Our proposal parameter configuration is as follows
- Move all the parameter files in autoware.universe/launch/tier4_*_launch/config to autoware_launch/config (We name this “launch parameters”)
- Create a parameter configuration file that lists all the “launch parameters” for each components
- In tier4_*_launch, the launch files loads the “launch parameter” if the argument is given in the parameter configuration file.

![Screenshot from 2022-12-08 18-17-39](https://user-images.githubusercontent.com/44218668/206414329-87cc380d-1f72-4ff9-8c57-aac95083c03c.png)


# Pros & Cons

Pros
- You can customize the Autoware parameters just by forking autoware_launch repository.

Cons
- You would not be able to launch tier4_*_launch only within autoware.universe since it will require “launch parameters” which is stored in autoware_launch any longer.

# Possible effects
- Launch configuration of tier4_*_launch will be changed as described above. 
  - If you are using original tier4_*_launch and your own customized autoware.launch.xml, make sure to incorporate the above change.
  - It won’t be a problem as long as you are using the same version of autoware.universe and autoware_launch.

**Comment by kenji-miyake** [comment]
@kminoda Thank you for your proposal! :smile: Generally it looks good to me, but some details are different from what I thought.

This was my assumption. What do you think?

```xml
// autoware_launch/launch/autoware.launch.xml
<include file="$(find-pkg-share autoware_launch)/launch/components/tier4_localization.launch.xml"/>
```

```xml
// autoware_launch/launch/components/tier4_localization.launch.xml
<include file="$(find-pkg-share tier4_localization_launch)/launch/localization.launch.xml">
  <arg name="foo_param_path" value="foo" />
  <arg name="bar_param_path" value="bar" />
</include>
```

```xml
// tier4_localization_launch/launch/localization.launch.xml
<arg name="foo_param_path" />
<arg name="bar_param_path" />

<include file="$(find-pkg-share foo)/launch/foo.launch.xml">
  <arg name="foo_param_path" value="$(var foo_param_path)" />
</include>

<include file="$(find-pkg-share bar)/launch/bar.launch.xml">
  <arg name="bar_param_path" value="$(var bar_param_path)" />
</include>
```

**Comment by kminoda** [comment]
@kenji-miyake Thank you! After internal discussion, let me modify the above proposal a bit.

--
# Proposal

Our proposal parameter configuration is as follows
- Move all the parameter files in `autoware.universe/launch/tier4_*_launch/config` to `autoware_launch/config` (We name this “launch parameters”)
- Create a component launch script in autoware_launch in which we list all the “launch parameters” in the arguments.
  - `autoware_launch/launch/components/tier4_localization_component.launch.xml` in the figure.
- `tier4_*_launch` in `autoware.universe` will use the parameter file designated in the above component launch script.
![image](https://user-images.githubusercontent.com/44218668/206819089-ced0c482-6236-4be8-86ef-f91647c37e11.png)


Please refer to these PRs for example
- [autoware.universe](https://github.com/autowarefoundation/autoware.universe/pull/2479)
- [autoware_launch](https://github.com/autowarefoundation/autoware_launch/pull/124)



# Pros & Cons

Pros
- You can customize the Autoware parameters just by forking `autoware_launch` repository.

Cons
- You would not be able to launch `tier4_*_launch` only within `autoware.universe` since it will require “launch parameters” which is stored in `autoware_launch` any longer. (You can still use the default parameters in each packages to launch `tier4_*_launch` within `autoware.universe`)

# Possible effects
- Launch configuration of `tier4_*_launch`  will be changed as described above. 
  - If you are using original `tier4_*_launch`  and your own customized `autoware.launch.xml`, make sure to incorporate the above change.
  - It won’t be a problem as long as you are using the same version of `autoware.universe` and `autoware_launch`.

**Comment by kminoda** [comment]
We are going to start implementing the above proposal from December 19th.
Let us know if you have any comments until then. (cc. @xmfcx)

**Comment by xmfcx** [comment]
@kminoda @takayuki5168 will there be any automated mechanism that would check these launch files work as expected?

And they are kept updated? (Since they are now going to be more separated.)

I am glad we are reducing the number of launch files, it is very annoying to track how launch files are connected to each other.

**Comment by kminoda** [comment]
@xmfcx Thank you for the reply!
As for now, we do not have any concrete plans for automated mechanisms as you have proposed in the previous comment, since we are focusing solely on reducing the number of parameter and launch files for better maintenance capability.

> And they are kept updated? (Since they are now going to be more separated.)

Sorry I could not get what you meant here, but if you asked if the `tier4_localization_components.launch.xml` files are going to be kept updated, yes they are. We are also going to add some descriptions about how to update these files in the Autoware Documentation.

**Comment by xmfcx** [comment]
> We are also going to add some descriptions about how to update these files in the Autoware Documentation.

@kminoda that's great, thanks for working on this!

**Comment by kminoda** [comment]
Progress:
- system
  - https://github.com/autowarefoundation/autoware.universe/pull/2540
  - https://github.com/autowarefoundation/autoware_launch/pull/130
- perception
  - https://github.com/autowarefoundation/autoware.universe/pull/2539
  - https://github.com/autowarefoundation/autoware_launch/pull/131
- localization
  - https://github.com/autowarefoundation/autoware.universe/pull/2537
  - https://github.com/autowarefoundation/autoware_launch/pull/129
- map
  - https://github.com/autowarefoundation/autoware.universe/pull/2538
  - https://github.com/autowarefoundation/autoware_launch/pull/128

**Comment by kminoda** [comment]
The proposed modification has been merged to autoware.universe and autoware_launch.
